### ISSUE TITLE
求教~，直接运行maml.py文件跑不通，因为需要将config配置好，可否提供一个跑的sh命令行呢

### ISSUE THREAD

**Issue by fanzhang2021** [fewshotcdcs/CDCS#3]
或者别的能跑通的。谢谢了

**Comment by fewshotcdcs** [comment]
文档会在之后完善，模型以及训练的参数可以在论文中获得

**Comment by guxd** [comment]
``python maml.py --data_dir dataset/ --model_type roberta --model_name_or_path microsoft/codebert-base --task_name codesearch --output_dir output --do_meta_train --train_file train/file.tsv``
