### ISSUE TITLE
请问能否共享一下，通过预训练和MAML算法训练后的模型

### ISSUE THREAD

**Issue by fanzhang2021** [fewshotcdcs/CDCS#4]
麻烦您可以提供一个：在java和python语料库上，通过预训练和MAML算法训练完成的模型，让我可以直接在sql和solidity上进行微调。（即经过论文 3.2Pre-training 和 3.3Meta Learning着这两个阶段后，训练的模型）

因为这样可以省去复现的时间，以及复现时误差。
且能更准确的将您的论文作为baseline。

非常感谢。

**Comment by guxd** [comment]
https://github.com/fewshotcdcs/CDCS/releases/tag/v1.0.0
