### ISSUE TITLE
Lack of proper evaluation metrics

### ISSUE THREAD

**Issue by jordane95** [fewshotcdcs/CDCS#5]
I noticed that you reported accuracy@k and MRR in your paper. But I can't find corresponding implementation in your code.

Actually, I only find accuracy and f1, which are used to evaluate binary classification models.

**Comment by Gumooc** [comment]
For the construction of search tasks, you can refer to section 3.5 in the paper. By selecting all data in the test set as candidates, and then you can calculate the accuracy@k and MRR.

**Comment by fewshotcdcs** [comment]
For the construction of search task, you can refer to section 3.5 in the paper. By selecting all data in the test set as candidates, the accuracy@k and MRR metrics can be calculated.

**Comment by jordane95** [comment]
Thanks for your reply!
